#ifndef KEYSIGNATURESPINBOX_GLOBAL_HPP
#define KEYSIGNATURESPINBOX_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(KEYSIGNATURESPINBOX_LIBRARY)
#  define KEYSIGNATURESPINBOX_EXPORT Q_DECL_EXPORT
#else
#  define KEYSIGNATURESPINBOX_EXPORT Q_DECL_IMPORT
#endif

#endif // KEYSIGNATURESPINBOX_GLOBAL_HPP
